### ISSUE TITLE
Expediting the Spark process

### ISSUE THREAD

**Issue by jinnycho** [jinnycho/safecast-radioactivity#17]
While manually making the dataset smaller helped facilitating the spark job, I think I should learn how to speed up the process more programmatically.

- Related PR: https://github.com/jinnycho/safecast-radioactivity/pull/16#issuecomment-511261311

## Todo
- [ ] Understand better about how `cache()` works.
- [ ] Understand better about how partitioning works.
- [ ] Understand better about how memory configuration works.
